import Head from "next/head";

//Components
import Layout from "../components/layout";
import SectionTitle from "../components/SectionTitle";
import ContentGrid from "../components/ContentGrid";
import ProjectSmallCard from "../components/project/ProjectSmallCard";
import TicketCard from "../components/ticket/TicketCard";
import LinkButton from "../components/LinkButton";
import ContentList from "../components/ContentList";
import ProjectCard from "../components/project/ProjectCard";

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Issue Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <SectionTitle title="Pinned Project" />
        <ContentGrid>
          <ProjectSmallCard
            img="https://i.pravatar.cc/25"
            name="Redit"
            description="Reddit is a network of communities where people can dive into their
        interests, hobbies and passions. There's a community for whatever you're
        interested in on Reddit."
          />
        </ContentGrid>

        <SectionTitle title="New Tickets" />
        <ContentGrid>
          <TicketCard
            title="Problem With Creating New Post"
            description="Sed pretium, turpis justo viverra feugiat. Varius ut gravida pharetra
        turpis vulputate eget libero, eget bibendum."
            priority="normal"
            assignedBy="John Doe"
          />
          <TicketCard
            title="Posts Not Showing After Choosing Priority"
            description="Sed pretium, turpis justo viverra feugiat. Varius ut gravida pharetra
        turpis vulputate eget libero, eget bibendum."
            priority="critical"
            assignedBy="John Doe"
          />
        </ContentGrid>
        <LinkButton txt="See All" dist="#" />

        <SectionTitle title="Project" />
        <ContentList>
          <ProjectCard
            img="https://i.pravatar.cc/50"
            title="Reddit"
            startedAt="10:30 | 1/16/2022"
            manager="John Doe"
            description="Nisl, ullamcorper duis tincidunt nibh et risus aliquam suscipit metus. Orci, tortor blandit fusce pellentesque at eget dignissim erat. Natoque phasellus quis erat bibendum nulla cras. Metus eu sit vitae orci convallis. Amet, suspendisse eget dignissim cras sed et, vulputate. Ac vestibulum id ipsum mauris ..."
          />
          <ProjectCard
            img="https://i.pravatar.cc/50"
            title="Reddit"
            startedAt="10:30 | 1/16/2022"
            manager="John Doe"
            description="Nisl, ullamcorper duis tincidunt nibh et risus aliquam suscipit metus. Orci, tortor blandit fusce pellentesque at eget dignissim erat. Natoque phasellus quis erat bibendum nulla cras. Metus eu sit vitae orci convallis. Amet, suspendisse eget dignissim cras sed et, vulputate. Ac vestibulum id ipsum mauris ..."
          />
        </ContentList>
      </Layout>
    </>
  );
}
