import { useEffect, useState } from "react";
import Head from "next/head";

// Firebase
import { auth, firestore } from "../firebase";
import { collection, getDocs, limit, query } from "firebase/firestore";

//Components
import Layout from "../components/layout";
import SectionTitle from "../components/SectionTitle";
import ContentGrid from "../components/ContentGrid";
import ProjectSmallCard from "../components/project/ProjectSmallCard";
import TicketCard from "../components/ticket/TicketCard";
import LinkButton from "../components/LinkButton";
import ContentList from "../components/ContentList";
import ProjectCard from "../components/project/ProjectCard";

export default function Dashboard() {
  const [projects, setProjects] = useState([]);
  useEffect(() => {
    const getDocsCollectionRef = collection(firestore, "Projects");
    const getDocsQueryRef = query(getDocsCollectionRef, limit(3));
    getDocs(getDocsQueryRef).then((data) => {
      const tempData = data.docs.map((item) =>
        Object.assign(item.data(), { id: item.id })
      );
      setProjects(tempData);
    });
  }, []);

  return (
    <>
      <Head>
        <title>Issue Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <SectionTitle title="Pinned Project" />
        <ContentGrid>
          <ProjectSmallCard
            img="https://i.pravatar.cc/25"
            name="Redit"
            description="Reddit is a network of communities where people can dive into their
        interests, hobbies and passions. There's a community for whatever you're
        interested in on Reddit."
          />
        </ContentGrid>

        <SectionTitle title="New Tickets" />
        <ContentGrid>
          <TicketCard
            title="Problem With Creating New Post"
            description="Sed pretium, turpis justo viverra feugiat. Varius ut gravida pharetra
        turpis vulputate eget libero, eget bibendum."
            priority="normal"
            assignedBy="John Doe"
          />
          <TicketCard
            title="Posts Not Showing After Choosing Priority"
            description="Sed pretium, turpis justo viverra feugiat. Varius ut gravida pharetra
        turpis vulputate eget libero, eget bibendum."
            priority="critical"
            assignedBy="John Doe"
          />
        </ContentGrid>

        <SectionTitle title="Project" />
        <ContentList>
          {projects.length > 0 &&
            projects.map((project) => (
              <ProjectCard
                key={project.id}
                id={project.id}
                img={project.icon}
                title={project.title}
                startedAt={project.createdAt}
                manager={project.manager}
                description={project.description}
              />
            ))}
        </ContentList>
      </Layout>
    </>
  );
}
